# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostler < Formula
  desc "CLI tool to manage local development domains with nginx"
  homepage "https://github.com/serhiitroinin/hostler"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/serhiitroinin/hostler/releases/download/v1.1.0/hostler_1.1.0_darwin_amd64.tar.gz"
      sha256 "7c68ee10fdca9ebd7d5d0a2012db9211ed885f0e0dbcb218a49575076c0dd963"

      def install
        bin.install "hostler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/serhiitroinin/hostler/releases/download/v1.1.0/hostler_1.1.0_darwin_arm64.tar.gz"
      sha256 "76e9a9520c0087388ae8909ad787d75946488c52a159965101714a962b56a5db"

      def install
        bin.install "hostler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/serhiitroinin/hostler/releases/download/v1.1.0/hostler_1.1.0_linux_amd64.tar.gz"
      sha256 "17b9a5730d5253d77865195654f9a4777c6203c0b53afe5ddacff49f073122e3"
      def install
        bin.install "hostler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/serhiitroinin/hostler/releases/download/v1.1.0/hostler_1.1.0_linux_arm64.tar.gz"
      sha256 "7e005e2b83b91c07322383986ab4b238b3ef7a676afaf0f8871fd7f6bf623713"
      def install
        bin.install "hostler"
      end
    end
  end

  def caveats
    <<~EOS
      hostler requires nginx to be installed:
        brew install nginx

      Most commands require sudo:
        sudo hostler add myapp.loc 3000
    EOS
  end

  test do
    system "#{bin}/hostler", "--version"
  end
end
