# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostler < Formula
  desc "CLI tool to manage local development domains with nginx"
  homepage "https://github.com/serhiitroinin/hostler"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/serhiitroinin/hostler/releases/download/v1.0.0/hostler_1.0.0_darwin_amd64.tar.gz"
      sha256 "2be095695fc1e8fbf1924b83ce29c726b70b6e344f71216effcb4981e112c989"

      def install
        bin.install "hostler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/serhiitroinin/hostler/releases/download/v1.0.0/hostler_1.0.0_darwin_arm64.tar.gz"
      sha256 "73740e1dd090c94e4023ec1d074657faa97d4fdb7ce178759e3e806b24726604"

      def install
        bin.install "hostler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/serhiitroinin/hostler/releases/download/v1.0.0/hostler_1.0.0_linux_amd64.tar.gz"
      sha256 "c189d6586760c6c6374c0ce4cd215fb9251138efddbd97e9bf83ad89da056add"
      def install
        bin.install "hostler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/serhiitroinin/hostler/releases/download/v1.0.0/hostler_1.0.0_linux_arm64.tar.gz"
      sha256 "1cd5c37614df63bd72d893ec79f71529952a766c5dae57a66511a2280822d4ef"
      def install
        bin.install "hostler"
      end
    end
  end

  def caveats
    <<~EOS
      hostler requires nginx to be installed:
        brew install nginx

      Most commands require sudo:
        sudo hostler add myapp.loc 3000
    EOS
  end

  test do
    system "#{bin}/hostler", "--version"
  end
end
